Django_Tarafdari_Clone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('teams/', include('teams.urls', namespace='teams'))
             ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('password/reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('password/reset-confirm/<uidb64>/<token>/', views.UserPasswordConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password/change/', views.UserChangePasswordView.as_view(), name='change_password'),
    path('profile/', views.UserProfileView.as_view(), name='profile_without_pk'),
    path('profile/<int:pk>/', views.UserProfileView.as_view(), name='profile'),
    path('profile/edit/', views.UserProfileEditView.as_view(), name='edit_profile'),
    path('profile/follow-requests/', views.UserFollowRequestsView.as_view(), name='follow_requests'),
    path('profile/follow-request/<int:pk>/decision/', views.UserFollowRequestDecisionView.as_view(),
         name='follow_request_decision'),
    path('profile/block-reports-list/', views.UserBlockReportsView.as_view(), name='block_reports'),
    path('profile/block-report/<int:pk>/delete/', views.UserBlockReportDeleteView.as_view(),
         name='block-report_delete'),
    path('user/<int:pk>/block-report/', views.UserBlockReportView.as_view(), name='block_report'),
    path('follow/user/<int:pk>/', views.UserFollowView.as_view(), name='user_follow'),
    path('unfollow/user/<int:pk>/', views.UserUnfollowView.as_view(), name='user_unfollow'),
    path('follow-request/user/<int:pk>/', views.UserFollowRequestView.as_view(), name='user_follow_request'),
    path('unfollow-request/user/<int:pk>/', views.UserUnfollowRequestView.as_view(), name='user_unfollow_request'),
    path('emoji/pack/user/<int:pk>/', views.UserEmojiPackageView.as_view(), name='emoji_package'),
    path('profile/phone-verify/', views.UserPhoneVerifyView.as_view(), name='phone_verify'),
]

teams/urls.py
from django.urls import path
from . import views

app_name = 'teams'
urlpatterns = [
    path('<str:league>/', views.ListTeamsView.as_view(), name='list_teams'),
    path('<str:team>/follow/', views.FollowTeamView.as_view(), name='follow_team'),
    path('<str:team>/unfollow/', views.UnfollowTeamView.as_view(), name='unfollow_team'),
]

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField, SetPasswordForm, PasswordChangeForm
from django.contrib.auth import password_validation
from .models import UserModel, OTPCodeModel, BlockModel
from random import randint


class UserLoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={"autofocus": True, 'placeholder': 'ایمیل / موبایل'}),
                             label='نام کاربری', error_messages={'required': 'نام کاربری اجباری است'})
    password = forms.CharField(label='رمز عبور', strip=False,
                               widget=forms.PasswordInput(attrs={"autocomplete": "current-password"}),
                               error_messages={'required': 'رمز عبور اجباری است'})
    error_messages = {
        'invalid_login': 'رمز عبور یا ایمیل نامعتبر است',
        'inactive': 'این حساب غیرفعال شده است'
    }


class UserRegisterForm(forms.ModelForm):
    password1 = forms.CharField(label='رمز عبور', widget=forms.PasswordInput(),
                                error_messages={'required': 'رمز عبور الزامی است'})
    password2 = forms.CharField(label='تکرار رمز عبور', widget=forms.PasswordInput(),
                                error_messages={'required': 'رمز عبور الزامی است'})

    class Meta:
        model = UserModel
        fields = ('first_name', 'last_name', 'phone_number', 'email')
        labels = {
            'first_name': 'نام',
            'last_name': 'نام خانوادگی',
            'phone_number': 'موبایل',
            'email': 'ایمیل',
        }
        error_messages = {
            'first_name': {'required': 'نام الزامی است'},
            'last_name': {'required': 'نام خانوادگی الزامی است'},
            'phone_number': {'required': 'شماره تلفن الزامی است'},
            'email': {'required': 'ایمیل الزامی است'}
        }

    def clean(self):
        cd = super().clean()
        p1 = cd.get('password1')
        p2 = cd.get('password2')
        if p1 and p2 and (p1 != p2):
            raise forms.ValidationError('رمز عبور نادرست میباشد')
        return cd

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = UserModel.objects.normalize_email(self.cleaned_data['email'])
        user.set_password(self.cleaned_data['password2'])
        user.is_phone_verified = False
        otp_code = OTPCodeModel.objects.create(phone_number=user.phone_number, code=randint(100000, 999999))
        otp_code.send_otp_code()
        if commit:
            user.save()
        return user


class UserPasswordConfirmForm(SetPasswordForm):
    error_messages = {
        "password_mismatch": 'دو رمز عبور تطابق ندارند',
    }
    new_password1 = forms.CharField(
        label='رمز عبور جدید',
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label='تایید رمز عبور جدید',
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
    )


class UserChangePasswordForm(UserPasswordConfirmForm):
    error_messages = {
        **SetPasswordForm.error_messages,
        "password_incorrect": 'رمز عبور قدیمی شما نامعتبر است'}
    old_password = forms.CharField(
        label="رمز عبور فعلی", strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password", "autofocus": True}), )


class UserProfileEditForm(forms.ModelForm):
    class Meta:
        model = UserModel
        fields = ['first_name', 'last_name', 'profile_image', 'cover_image', 'background_image', 'is_private',
                  'about_me', 'email']
        widgets = {
            'profile_image': forms.FileInput(),
        }


class UserPhoneVerifyForm(forms.Form):
    otp_code = forms.CharField(label='کد ارسالی', max_length=6)


class UserBlockReportForm(forms.ModelForm):
    class Meta:
        model = BlockModel
        fields = ['reason']
        widgets = {
            'reason': forms.RadioSelect()
        }

accounts/views.py
from random import randint
from utils import UnauthenticatedRequiredMixin, ProfileContextMixin, UnBlockedRequiredMixin, \
    PublicUserProfileRequiredMixin, PrivateUserProfileRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, FormView, ListView, DetailView, UpdateView, DeleteView, View
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetConfirmView, \
    PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from .models import UserModel, FollowModel, EmojiPackageModel, BlockModel, FollowRequestModel, OTPCodeModel
from .forms import UserRegisterForm, UserLoginForm, UserPasswordConfirmForm, UserChangePasswordForm, \
    UserProfileEditForm, UserPhoneVerifyForm, UserBlockReportForm


class UserLoginView(UnauthenticatedRequiredMixin, LoginView):
    """A view for handling user login functionality."""

    template_name = 'accounts/login.html'
    redirect_authenticated_user = True
    form_class = UserLoginForm


class UserLogoutView(LoginRequiredMixin, LogoutView):
    """A view for handling user logout functionality."""

    next_page = reverse_lazy('accounts:login')


class UserRegisterView(UnauthenticatedRequiredMixin, SuccessMessageMixin, CreateView):
    """A view for handling user registration functionality."""

    model = UserModel
    form_class = UserRegisterForm
    template_name = 'accounts/register.html'
    success_message = 'شما با موفقیت ثبت نام کردید'
    success_url = reverse_lazy('accounts:login')


class UserPasswordResetView(UnauthenticatedRequiredMixin, SuccessMessageMixin, PasswordResetView):
    """A view for handling user password reset functionality."""

    template_name = 'accounts/password_reset.html'
    email_template_name = 'accounts/password_reset_email.html'
    html_email_template_name = 'accounts/password_reset_email.html'
    success_message = 'ایمیل با موفقیت برای شما ارسال شد'
    success_url = reverse_lazy('accounts:login')


class UserPasswordConfirmView(UnauthenticatedRequiredMixin, SuccessMessageMixin, PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'
    success_message = 'رمز عبور شما با موفقیت تغییر کرد'
    success_url = reverse_lazy('accounts:login')
    form_class = UserPasswordConfirmForm


class UserProfileView(ProfileContextMixin, LoginRequiredMixin, UnBlockedRequiredMixin, DetailView):
    template_name = 'accounts/profile.html'
    model = UserModel
    context_object_name = 'user'

    def dispatch(self, request, *args, **kwargs):
        if kwargs.get('pk') is None:
            return redirect('accounts:profile', pk=request.user.pk)
        return super().dispatch(request, *args, **kwargs)


class UserFollowView(LoginRequiredMixin, UnBlockedRequiredMixin, PublicUserProfileRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        user = UserModel.objects.get(pk=kwargs['pk'])
        FollowModel.objects.update_or_create(from_user=request.user, to_user=user)
        return redirect('accounts:profile', pk=kwargs['pk'])


class UserUnfollowView(LoginRequiredMixin, UnBlockedRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        FollowModel.objects.get(from_user=self.request.user, to_user=kwargs['pk']).delete()
        return redirect('accounts:profile', pk=kwargs['pk'])


class UserFollowRequestView(LoginRequiredMixin, UnBlockedRequiredMixin, PrivateUserProfileRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user = UserModel.objects.get(pk=kwargs['pk'])
        FollowRequestModel.objects.update_or_create(from_user=request.user, to_user=user)
        return redirect('accounts:profile', pk=kwargs['pk'])


class UserUnfollowRequestView(LoginRequiredMixin, UnBlockedRequiredMixin, DeleteView):

    def get(self, request, *args, **kwargs):
        FollowRequestModel.objects.get(from_user=self.request.user, to_user=kwargs['pk']).delete()
        return redirect('accounts:profile', pk=kwargs['pk'])


class UserEmojiPackageView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        emoji_package = EmojiPackageModel.objects.get(from_user=request.user,
                                                      to_user=UserModel.objects.get(pk=kwargs['pk']))
        emoji_request = request.GET.get('emoji')
        match emoji_request:
            case 'heart':
                emoji_package.reverse_heart_emoji()
            case 'trophy':
                emoji_package.reverse_trophy_emoji()
            case 'passion':
                emoji_package.reverse_passion_emoji()
            case _:
                pass
        return redirect('accounts:profile', pk=kwargs['pk'])


class UserProfileEditView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    template_name = 'accounts/edit_profile.html'
    success_message = 'اطلاعات شما با موفقیت تغییر کرد'
    form_class = UserProfileEditForm

    def get_object(self, queryset=None):
        return self.request.user


class UserChangePasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'accounts/change_password.html'
    success_message = 'رمز عبور شما با موفقیت تغییر کرد'
    form_class = UserChangePasswordForm


class UserFollowRequestsView(LoginRequiredMixin, ProfileContextMixin, ListView):
    template_name = 'accounts/follow_requests.html'
    context_object_name = 'follower_requests'

    def get_queryset(self):
        return self.request.user.followers_request.all()


class UserFollowRequestDecisionView(View):
    def get(self, request, *args, **kwargs):
        follow_request = FollowRequestModel.objects.get(from_user=UserModel.objects.get(pk=kwargs['pk']),
                                                        to_user=request.user)
        decision = request.GET.get('decision')
        match decision:
            case 'accept':
                follow_request.accept()
            case 'reject':
                follow_request.reject()
        return redirect('accounts:follow_requests')


class UserBlockReportsView(LoginRequiredMixin, ProfileContextMixin, ListView):
    template_name = 'accounts/block_reports.html'
    context_object_name = 'blocked_users'

    def get_queryset(self):
        queryset = self.request.user.blocked_by.all()
        return queryset


class UserBlockReportDeleteView(LoginRequiredMixin, ProfileContextMixin, SuccessMessageMixin, DeleteView):
    success_url = reverse_lazy('accounts:block_reports')
    success_message = 'شما این کاربر را آنبلاک کرده اید'

    def get_object(self, queryset=None):
        return BlockModel.objects.get(from_user=self.request.user, to_user=self.kwargs['pk'])

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)


class UserPhoneVerifyView(LoginRequiredMixin, ProfileContextMixin, FormView):
    template_name = 'accounts/phone_verify.html'

    form_class = UserPhoneVerifyForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_phone_verified:
            messages.success(request, 'شماره تلفن شما تایید شده است')
            return redirect('accounts:profile_without_pk')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = self.request.user
        code = form.cleaned_data['otp_code']
        if 'send-again' in form.data:
            otp_code = OTPCodeModel.objects.update_or_create(phone_number=self.request.user.phone_number,
                                                             code=randint(100000, 999999))
            otp_code.send_otp_code()
            return render(self.request, self.template_name, {'form': self.form_class()})
        code_instance = OTPCodeModel.objects.get(phone_number=user.phone_number).code
        if code == code_instance:
            user.is_phone_verified = True
            user.save()
            messages.success(self.request, 'شماره تلفن شما با موفقیت تایید شد')
            return redirect('accounts:profile_without_pk')
        messages.error(self.request, 'کد وارد شده نادرست میباشد')
        return self.form_invalid(form)

    def form_invalid(self, form):
        if 'send-again' in form.data:
            otp_code = OTPCodeModel.objects.get(phone_number=self.request.user.phone_number)
            otp_code.code = randint(100000, 999999)
            otp_code.send_otp_code()
            otp_code.save()
            return render(self.request, self.template_name, {'form': self.form_class()})
        return render(self.request, self.template_name, {'form': form})


class UserBlockReportView(ProfileContextMixin, LoginRequiredMixin, UnBlockedRequiredMixin, FormView):
    template_name = 'accounts/block_report.html'
    form_class = UserBlockReportForm

    def form_valid(self, form):
        user = UserModel.objects.get(pk=self.kwargs['pk'])
        BlockModel.objects.create(from_user=self.request.user, to_user=user,
                                  reason=form.cleaned_data['reason'])
        return redirect('accounts:profile_without_pk')


class UserFollowingListView(ListView):
    paginate_by = 20
    template_name = 'accounts/'

    def get_queryset(self):
        return UserModel.objects.get(pk=self.kwargs['pk']).followings.all()


class UserFollowersListView(ListView):
    paginate_by = 20
    template_name = accounts

    def get_queryset(self):
        return UserModel.objects.get(pk=self.kwargs['pk']).followings.all()

accounts/templates/accounts/base_profile.html
{% extends 'base.html' %}
{% load static %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'accounts/css/base_profile.css' %}">
    {% block other_stylesheet %}{% endblock %}
    <style>
        {% if user.background_image %}
            body {
                background: url({{ user.background_image.url }}) no-repeat center center fixed;
                background-size: cover;
            }
        {% endif %}

        i.tarafdari-icons, i.update-icon, i.follow-icon, i.last-online, i.registration-date, #add-post h2 i,
        #add-post h2 a {
            background-image: url({% static 'defaults/Tarafdari-icons.png' %});
            background-repeat: no-repeat;
        }

        {% if user.is_online %}
            .status i {
                background-position: 0 -200px;
            }
        {% endif %}
    </style>
{% endblock %}
{% block body %}
    {# block form errors #}
    {% if form %}
        {% if form.errors %}
            <div id="form-errors" class="container my-3">
                {{ form.non_field_errors }}
                {% for field in form %}
                    {% if field.errors %}
                        {{ field.errors }}
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
    {% endif %}
    {# endblock form errors #}
    {# block tabs #}
    {% include 'accounts/base_profile_tabs.html' %}
    {# endblock tabs #}
    {# block page user #}
    <div id="page-user" class="pb-3">
        <div class="container">
            <div id="cover-image" style="position: relative">
                <div id="item">
                    <img src="{{ user.cover_image.url }}" width="1050" height="250">
                </div>
                <span class="user-picture">
                <a href="{{ user.get_absolute_url }}" title="مشاهده پروفایل کاربر">
                        <img src="{{ user.profile_image.url }}" width="128" height="128">
                </a>
            </span>
            </div>
            <div id="tools" class="d-flex justify-content-between">
                <div id="tools-1" class="d-flex flex-row carousel">
                    <h2 class="status">
                        <a href="{{ user.get_absolute_url }}">{{ user.full_name }}</a>
                        <i class="tarafdari-icons"></i>
                    </h2>
                    <div>
                        {% if is_owner %}
                            <a class="update" style="cursor: pointer" href="{% url 'accounts:edit_profile' %}"><i
                                    class="update-icon"></i>ویرایش پروفایل</a>
                        {% else %}
                            {% if is_followed %}
                                <a class="follow-button" href="{% url 'accounts:user_unfollow' user.pk %}"><i
                                        class="follow-icon"></i>توقف دنبال کردن</a>
                            {% elif user.is_private %}
                                {% if is_follow_requested %}
                                    <a class="follow-button"
                                       href="{% url 'accounts:user_unfollow_request' user.pk %}"><i
                                            class="follow-icon"></i>حذف درخواست</a>

                                {% else %}<a class="follow-button"
                                             href="{% url 'accounts:user_follow_requestst' user.pk %}"><i
                                        class="follow-icon"></i>درخواست فالو</a>

                                {% endif %}
                            {% else %}<a class="follow-button" href="{% url 'accounts:user_follow' user.pk %}"><i
                                    class="follow-icon"></i>دنبال کن</a>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
                <div id="tools-2">
                    <a href="">آخرین مطالب</a>
                    <a href="">ویدیو</a>
                    <a href="">موزیک</a>
                    <a href="">تصاویر</a>
                    {% if is_owner %}
                        <a href="">خانه</a>
                    {% else %}
                        <a href="{% url 'accounts:block_report' user.pk %}">گزارش</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {# endblock pageuser #}
    {# block main #}
    <section id="main">
        <div class="container">
            <div class="row">
                <div class="col-4">
                    <div class="d-flex flex-column px-3 py-4">
                        <div id="emoji-package" class="pb-3">
                            {% if does_selected_emoji.heart %}
                                <a href="{% url 'accounts:emoji_package' user.pk %}?emoji=heart"
                                   class="emoji-heart selected">
                            {% else %}
                                <a href="{% url 'accounts:emoji_package' user.pk %}?emoji=heart" class="emoji-heart">
                            {% endif %}
                            {{ user.number_of_heart_emojis }}</a>
                            {% if does_selected_emoji.trophy %}
                                <a href="{% url 'accounts:emoji_package' user.pk %}?emoji=trophy"
                                   class="emoji-trophy selected">
                            {% else %}
                                <a href="{% url 'accounts:emoji_package' user.pk %}?emoji=trophy" class="emoji-trophy">
                            {% endif %}
                            {{ user.number_of_trophy_emojis }}</a>
                            {% if does_selected_emoji.passion %}
                                <a href="{% url 'accounts:emoji_package' user.pk %}?emoji=passion"
                                   class="emoji-passion selected">
                            {% else %}
                                <a href="{% url 'accounts:emoji_package' user.pk %}?emoji=passion"
                                   class="emoji-passion">
                            {% endif %}
                            {{ user.number_of_passion_emojis }}</a>
                        </div>
                        <div id="bio-section">
                            {% if user.about_me %}
                                {{ user.about_me|safe }}
                            {% endif %}
                        </div>
                        <div>
                            <div class="py-2">
                                <i class="last-online"></i>آخرین بازدید {{ user.last_online|timesince }} قبل
                            </div>
                            <div class="py-2">
                                <i class="registration-date"></i>عضویت از {{ user.registration_date|timesince }} قبل
                            </div>
                        </div>
                        <div>
                            <a href="" class="subscription">اشتراک</a>
                        </div>
                    </div>
                    <div class="my-3" id="add-post">
                        <h2><i></i><a></a>ارسال مطلب جدید</h2>
                        <div style="display: none">
                            <ul>
                                <li><a href="">کاربر: تصویر</a></li>
                                <li><a href="">کاربر: صوت</a></li>
                                <li><a href="">کاربر: سوال</a></li>
                                <li><a href="">کاربر: مطلب</a></li>
                                <li><a href="">کاربر: ویدیو</a></li>
                            </ul>
                        </div>
                    </div>
                    <div id="block-followings">
                        <h2>دنبال شوندگان
                            <a href="">{{ followings_count }}</a>
                        </h2>
                        <div class="row">
                            {% for following in followings %}
                                <span class="col-4"><a href="{{ following.get_absolute_url }}">
                                <img src="{{ following.profile_image.url }}" width="128" height="128"
                                     title="{{ following.full_name }}">
                            </a></span>
                            {% endfor %}
                        </div>
                    </div>
                    <div id="block-followers" class="my-3">
                        <h2>دنبال کنندگان
                            <a href="">{{ followers_count }}</a>
                        </h2>
                        <div class="row">
                            {% for follower in followers %}
                                <span class="col-4"><a href="{{ follower.get_absolute_url }}">
                                <img src="{{ follower.profile_image.url }}" width="128" height="128"
                                     title="{{ follower.full_name }}">
                            </a></span>
                            {% endfor %}
                        </div>
                    </div>

                    <div id="block-teams" class="my-3">
                        <h2>تیم های مورد علاقه
                            <a href="{% url 'teams:list_teams' 'all' %}">لیست تیم ها</a>
                        </h2>
                        <div class="row">
                            {% for team in following_teams %}
                                <div class="col-12">
                                    <a href="">
                                        <img src="{{ team.logo.url }}" alt="{{ team.name }}" width="32"
                                             height="32"><span class="text-dark px-3">{{ team.name }}</span>
                                    </a>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div id="block-posts" class="my-3">
                        <h2>آخرین مطالب
                            <a href="">لیست</a>
                            <a href="">ایجاد</a>
                        </h2>
                        <div class="row">
                        </div>
                    </div>
                    <div id="block-upload" class="my-3">
                        <h2>آخرین فایل ها
                            <a href="">لیست</a>
                            <a href="">بارگذاری</a>
                        </h2>
                        <div class="row">
                        </div>
                    </div>
                    <div id="block-info" class="my-3">
                        <h2>عملکرد کاربر
                        </h2>
                        <div class="row">
                        </div>
                    </div>
                </div>
                <div class="col-8">
                    {% block main %}{% endblock %}
                </div>
            </div>
        </div>
    </section>
    {# endblock main #}
{% endblock %}

accounts/templates/accounts/base_profile_tabs.html
<style>
    #tabs ul {
        overflow: hidden;
        *zoom: 1;
        line-height: 34px;
        background-color: #474f57;
        color: #fff;
        padding-right: 0;
    }

    #tabs ul li {
        margin: 0;
        padding: 0;
        border: none !important;
        list-style: none;
    }

    #tabs ul li.active {
        background-color: #27bcc9;
    }
</style>
<section id="tabs" class="container my-3">
    <ul class="d-flex flex-row">
        <li class="px-2"><a href="{{ user.get_absolute_url }}">مشاهده</a></li>
        <li class="px-2"><a href="">استاتوس ها</a></li>
        {% if is_owner or is_owner is None %}
            <li class="px-2"><a href="{% url 'accounts:block_reports' %}">مسدود ها</a></li>
            <li class="px-2"><a href="{% url 'accounts:edit_profile' %}">ویرایش پروفایل</a></li>
            <li class="px-2"><a href="{% url 'accounts:change_password' %}">تغییر رمز</a></li>
            <li class="px-2"><a href="{% url 'accounts:follow_requests' %}">فالو ریکوئست ها</a></li>
            <li class="px-2"><a href="">پیام های خصوصی</a></li>
            <li class="px-2"><a href="{% url 'accounts:phone_verify' %}">تایید موبایل</a></li>
        {% endif %}
    </ul>
</section>

accounts/templates/accounts/block_report.html
{% extends 'accounts/base_profile.html' %}
{% load static %}
{% block other_stylesheet %}
    <link rel="stylesheet" href="{% static 'accounts/css/block_report.css' %}">
{% endblock %}
{% block title %}طرفداری | بلاک کردن کاربر{% endblock %}
{% block main %}
    <div class="block-form bg-white p-3">
        <h5>دلیل اینکه {{ user.full_name }} را بلاک میکنید</h5>
        <form action="" method="post">
        {% csrf_token %}
            {% for field in form.reason %}
                <div class="row py-2">
                {{ field }}
                </div>
            {% endfor %}
        <input type="submit" value="ارسال">
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>ایمیل بازیابی رمز طرفداری</title>
</head>
<body>
<h3>این ایمیل از طرف سایت طرفداری برای شما ارسال میشود.</h3>
<p>شما درخواست بازیابی رمز عبور کرده اید. از طریق لینک زیر میتوانید برای حساب خود رمز عبور جدیدی تنظیم کنید.</p>
<p>{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}</p>
</body>
</html>

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}عضویت | طرفداری{% endblock %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'accounts/css/register.css' %}">
{% endblock %}
{% block body %}
    {% if form.errors %}
        <div id="form-errors" class="container my-3">
            {{ form.non_field_errors }}
            {% for field in form %}
                {% if field.errors %}
                    {{ field.errors }}
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}
    <section id="tabs" class="container my-3 px-0">
        <ul class="d-flex flex-row">
            <li class="px-2 active"><a href="{% url 'accounts:register' %}">ایجاد اکانت جدید</a></li>
            <li class="px-2"><a href="{% url 'accounts:login' %}">ورود</a></li>
            <li class="px-2"><a href="{% url 'accounts:password_reset' %}">درخواست کلمه عبور جدید</a></li>
        </ul>
    </section>
    <section id="user-register-section">
        <div class="container py-3">
            <form action="" method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    <div class="row pb-3">
                        <div class="col-4">
                            {{ field.label }}
                        </div>
                        <div class="col-8">
                            {{ field }}
                        </div>
                    </div>
                {% endfor %}
                <div class="row">
                    <div class="col-8 offset-4">
                        <button type="submit">ایجاد اکانت جدید</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
{% endblock %}