Django_Tarafdari_Clone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('teams/', include('teams.urls', namespace='teams'))
             ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teams/urls.py
from django.urls import path
from . import views

app_name = 'teams'
urlpatterns = [
    path('<str:league>/', views.ListTeamsView.as_view(), name='list_teams'),
    path('<str:team>/follow/', views.FollowTeamView.as_view(), name='follow_team'),
    path('<str:team>/unfollow/', views.UnfollowTeamView.as_view(), name='unfollow_team'),
]

teams/models.py
from django.db import models
from django.urls import reverse
from accounts.models import UserModel


def team_logo_path(instance, filename):
    return f'teams/team_{instance.name}/{filename}'


class LeagueModel(models.Model):
    name = models.CharField(max_length=30, verbose_name='نام تیم', primary_key=True)

    class Meta:
        verbose_name = 'لیگ'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('teams:list_teams', kwargs={'league': self.name})


class TeamModel(models.Model):
    name = models.CharField(max_length=30, verbose_name='نام تیم', primary_key=True)
    logo = models.ImageField(upload_to=team_logo_path)
    league = models.ForeignKey(LeagueModel, on_delete=models.CASCADE, related_name='teams')
    followers = models.ManyToManyField(UserModel, through='UserFollowTeamModel', through_fields=('team', 'user'),
                                       related_name='following_teams')

    class Meta:
        verbose_name = 'تیم'

    def __str__(self):
        return self.name


class UserFollowTeamModel(models.Model):
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    team = models.ForeignKey(TeamModel, on_delete=models.CASCADE)
    datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user.full_name} - {self.team}'

    class Meta:
        unique_together = ('user', 'team')
        verbose_name = 'کاربر علاقمند به تیم'

teams/views.py
from django.shortcuts import redirect
from django.views.generic import ListView, DeleteView, View
from django.db.models import Case, When, BooleanField
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import TeamModel, LeagueModel, UserFollowTeamModel


class ListTeamsView(LoginRequiredMixin, ListView):
    template_name = 'teams/list_teams.html'
    context_object_name = 'teams'
    paginate_by = 20

    def get_queryset(self):
        if self.kwargs['league'] == 'all':
            teams = TeamModel.objects.all()
        else:
            teams = LeagueModel.objects.get(name=self.kwargs['league']).teams.all()
        return teams.annotate(
            is_followed=Case(
                When(followers=self.request.user, then=True),
                default=False,
                output_field=BooleanField()
            ), )

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['leagues'] = LeagueModel.objects.all()
        return context

    def get(self, request, *args, **kwargs):
        request.session['teams_url_path'] = request.path
        return super().get(request, *args, **kwargs)


class FollowTeamView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        team = TeamModel.objects.get(name=kwargs['team'])
        UserFollowTeamModel.objects.create(user=request.user, team=team)
        return redirect(request.session['teams_url_path'])


class UnfollowTeamView(LoginRequiredMixin, DeleteView):
    model = UserFollowTeamModel

    def get(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)

    def get_object(self, queryset=None):
        team = TeamModel.objects.get(name=self.kwargs['team'])
        return UserFollowTeamModel.objects.get(user=self.request.user, team=team)

    def get_success_url(self):
        return self.request.session['teams_url_path']

teams/templates/teams/list_teams.html
{% extends 'base.html' %}
{% load static %}
{% block title %}تیم ها | طرفداری{% endblock %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'teams/css/list_teams.css' %}">
{% endblock %}
{% block body %}
    <div class="container">
        <div class="row gy-3 mb-3">
            {% for league in leagues %}
                <div class="col-3 text-center league">
                    <a href="{{ league.get_absolute_url }}" class="px-3">{{ league.name }}</a></div>
            {% endfor %}
        </div>
    </div>
    <div class="container">
        <div class="row gy-3">
            {% for team in teams %}
                <div class="col-3">
                    <div class="card">
                        <img src="{{ team.logo.url }}" class="d-block mx-auto mt-2" alt="{{ team.name }}" width="128"
                             height="128">
                        <div class="card-body">
                            <h6 class="card-title text-center">{{ team.name }}</h6>
                            {% if team.is_followed %}
                                <a href="{% url 'teams:unfollow_team' team.name %}" class="unfollow-btn"
                                   team="{{ team.name }}">توقف دنبال کردن</a>
                            {% else %}
                                <a href="{% url 'teams:follow_team' team.name %}" class="follow-btn"
                                   team="{{ team.name }}">دنبال کن</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}