Django_Tarafdari_Clone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('teams/', include('teams.urls', namespace='teams'))
             ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('password/reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('password/reset-confirm/<uidb64>/<token>/', views.UserPasswordConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password/change/', views.UserChangePasswordView.as_view(), name='change_password'),
    path('profile/', views.UserProfileView.as_view(), name='profile_without_pk'),
    path('profile/<int:pk>/', views.UserProfileView.as_view(), name='profile'),
    path('profile/edit/', views.UserProfileEditView.as_view(), name='edit_profile'),
    path('profile/follow-requests/', views.UserFollowRequestsView.as_view(), name='follow_requests'),
    path('profile/follow-request/<int:pk>/decision/', views.UserFollowRequestDecisionView.as_view(),
         name='follow_request_decision'),
    path('profile/block-reports-list/', views.UserBlockReportsView.as_view(), name='block_reports'),
    path('profile/block-report/<int:pk>/delete/', views.UserBlockReportDeleteView.as_view(),
         name='block-report_delete'),
    path('user/<int:pk>/block-report/', views.UserBlockReportView.as_view(), name='block_report'),
    path('follow/user/<int:pk>/', views.UserFollowView.as_view(), name='user_follow'),
    path('unfollow/user/<int:pk>/', views.UserUnfollowView.as_view(), name='user_unfollow'),
    path('follow-request/user/<int:pk>/', views.UserFollowRequestView.as_view(), name='user_follow_request'),
    path('unfollow-request/user/<int:pk>/', views.UserUnfollowRequestView.as_view(), name='user_unfollow_request'),
    path('emoji/pack/user/<int:pk>/', views.UserEmojiPackageView.as_view(), name='emoji_package'),
    path('profile/phone-verify/', views.UserPhoneVerifyView.as_view(), name='phone_verify'),
]

teams/urls.py
from django.urls import path
from . import views

app_name = 'teams'
urlpatterns = [
    path('<str:league>/', views.ListTeamsView.as_view(), name='list_teams'),
    path('<str:team>/follow/', views.FollowTeamView.as_view(), name='follow_team'),
    path('<str:team>/unfollow/', views.UnfollowTeamView.as_view(), name='unfollow_team'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="https://www.tarafdari.com/sites/all/themes/hope_user/favicon.ico"
          type="image/vnd.microsoft.icon">
    <link rel="stylesheet" href="{% static 'css/bootstrap.rtl.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-icons/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block stylesheet %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{# block shortcuts#}
<div id="shortcuts">
    <section class="container">
        <div class="d-flex justify-content-between">
            <div id="shortcut-menu">
                <a href="">ارسال مطلب</a>
                <a href="">سایر ورزش ها</a>
                <a href="">مدیریت مطالب</a>
                <a href="">مطالب کاربران</a>
                <a href="">عضویت ویژه</a>
                <a href="">ویدیو</a>
                <a href="">جستجو</a>
                <a class="last" href="">گالری</a>
            </div>
            <div>
                <a class="night-toggle" href="">حالت شب</a>
            </div>
        </div>
    </section>
</div>
{# end block shortcuts#}
{# block header #}
<div id="header">
    <section class="container">
        <div class="row">
            <div class="col-2">
                <a class="logo" href="">
                    <img alt="طرفداری" src="https://www.tarafdari.com/sites/all/themes/hope/logo-desktop.svg?4">
                </a>
            </div>
            <div class="col-6">
                <div id="main-menu">
                    <a href="">نتایج زنده</a>
                    <a href="">طرفداری TV</a>
                </div>
            </div>
            <div class="col-4">
                {% if request.user.is_authenticated %}
                    <div class="notice-deliver text-center ms-3 py-auto">
                        <a href="">
                            {% if request.user.profile_image %}
                                <img src="{{ request.user.profile_image.url }}" width="34" height="34"
                                     style="border-radius: 5px">
                            {% else %}
                                <img src="{% static 'defaults/avatar-default.png' %}" width="34" height="34"
                                     style="border-radius: 5px">
                            {% endif %}
                        </a>
                    </div>
                    <div class="notice-deliver text-center ms-3 py-auto">
                        <a href="">
                            <i class="bi bi-list-task fs-4"></i>
                        </a>
                    </div>
                    <div class="notice-deliver text-center ms-3 py-auto">
                        <a href="">
                            <i class="bi bi-chat-dots-fill fs-4"></i>
                        </a>
                    </div>
                {% else %}
                    <div class="ms-3">
                        <a href="{% url 'accounts:login' %}" class="register-button">عضویت / ورود</a>
                    </div>
                {% endif %}
                <div>
                    <time style="color: #fff" id="time-header">چهارشنبه
                        ۱۷ اسفند ۱۳:۲۱
                    </time>
                </div>
            </div>
        </div>
    </section>
</div>
{# block messages #}
{% if messages %}
    {% for message in messages %}
        <div class="{{ message.tags }}-message container py-3 my-3">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
{# endblock messages #}
{# endblock header #}
{% block body %}{% endblock %}
{# block footer #}
<footer id="footer">
    <div class="container">
        <div class="d-flex flex-row">
            <a href="" class="pe-3">تبلیغات</a>
            <a href="" class="pe-3">درباره ما</a>
            <a href="" class="pe-3">همکاران</a>
            <a href="" class="pe-3">فرصت‌های شغلی</a>
            <a href="" class="pe-3">شرایط استفاده</a>
            <a href="" class="pe-3">تماس با ما</a>
            <a href="">آرشیو</a>
        </div>
        <div class="pt-5">
            <p>حق نشر © 2012 - 2020 طرفداری</p>
        </div>
    </div>
</footer>
{# end block footer #}

{# scripts #}
<script type="text/javascript" src="{% static 'js/bootstrap.bundle.js' %}"></script>
<script type="text/javascript" src="{% static 'js/base.js' %}"></script>
{% block scripts %}{% endblock %}
{#end scripts#}
</body>
</html>